// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/matlab/matlab-mcp-server/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMATLABClientProvider creates a new instance of MockMATLABClientProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMATLABClientProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMATLABClientProvider {
	mock := &MockMATLABClientProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMATLABClientProvider is an autogenerated mock type for the MATLABClientProvider type
type MockMATLABClientProvider struct {
	mock.Mock
}

type MockMATLABClientProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMATLABClientProvider) EXPECT() *MockMATLABClientProvider_Expecter {
	return &MockMATLABClientProvider_Expecter{mock: &_m.Mock}
}

// ClientWithSessionID provides a mock function for the type MockMATLABClientProvider
func (_mock *MockMATLABClientProvider) ClientWithSessionID(ctx context.Context, logger entities.Logger) (entities.MATLABSessionClient, entities.SessionID, error) {
	ret := _mock.Called(ctx, logger)

	if len(ret) == 0 {
		panic("no return value specified for ClientWithSessionID")
	}

	var r0 entities.MATLABSessionClient
	var r1 entities.SessionID
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger) (entities.MATLABSessionClient, entities.SessionID, error)); ok {
		return returnFunc(ctx, logger)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger) entities.MATLABSessionClient); ok {
		r0 = returnFunc(ctx, logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.MATLABSessionClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Logger) entities.SessionID); ok {
		r1 = returnFunc(ctx, logger)
	} else {
		r1 = ret.Get(1).(entities.SessionID)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, entities.Logger) error); ok {
		r2 = returnFunc(ctx, logger)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockMATLABClientProvider_ClientWithSessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClientWithSessionID'
type MockMATLABClientProvider_ClientWithSessionID_Call struct {
	*mock.Call
}

// ClientWithSessionID is a helper method to define mock.On call
//   - ctx context.Context
//   - logger entities.Logger
func (_e *MockMATLABClientProvider_Expecter) ClientWithSessionID(ctx interface{}, logger interface{}) *MockMATLABClientProvider_ClientWithSessionID_Call {
	return &MockMATLABClientProvider_ClientWithSessionID_Call{Call: _e.mock.On("ClientWithSessionID", ctx, logger)}
}

func (_c *MockMATLABClientProvider_ClientWithSessionID_Call) Run(run func(ctx context.Context, logger entities.Logger)) *MockMATLABClientProvider_ClientWithSessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Logger
		if args[1] != nil {
			arg1 = args[1].(entities.Logger)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMATLABClientProvider_ClientWithSessionID_Call) Return(mATLABSessionClient entities.MATLABSessionClient, sessionID entities.SessionID, err error) *MockMATLABClientProvider_ClientWithSessionID_Call {
	_c.Call.Return(mATLABSessionClient, sessionID, err)
	return _c
}

func (_c *MockMATLABClientProvider_ClientWithSessionID_Call) RunAndReturn(run func(ctx context.Context, logger entities.Logger) (entities.MATLABSessionClient, entities.SessionID, error)) *MockMATLABClientProvider_ClientWithSessionID_Call {
	_c.Call.Return(run)
	return _c
}
