// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/matlab/matlab-mcp-server/internal/entities"
	"github.com/matlab/matlab-mcp-server/internal/usecases/evalmatlabcode"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMATLABCodeEvaluator creates a new instance of MockMATLABCodeEvaluator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMATLABCodeEvaluator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMATLABCodeEvaluator {
	mock := &MockMATLABCodeEvaluator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMATLABCodeEvaluator is an autogenerated mock type for the MATLABCodeEvaluator type
type MockMATLABCodeEvaluator struct {
	mock.Mock
}

type MockMATLABCodeEvaluator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMATLABCodeEvaluator) EXPECT() *MockMATLABCodeEvaluator_Expecter {
	return &MockMATLABCodeEvaluator_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockMATLABCodeEvaluator
func (_mock *MockMATLABCodeEvaluator) Execute(ctx context.Context, sessionLogger entities.Logger, client entities.MATLABSessionClient, request evalmatlabcode.Args) (entities.EvalResponse, error) {
	ret := _mock.Called(ctx, sessionLogger, client, request)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 entities.EvalResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger, entities.MATLABSessionClient, evalmatlabcode.Args) (entities.EvalResponse, error)); ok {
		return returnFunc(ctx, sessionLogger, client, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entities.Logger, entities.MATLABSessionClient, evalmatlabcode.Args) entities.EvalResponse); ok {
		r0 = returnFunc(ctx, sessionLogger, client, request)
	} else {
		r0 = ret.Get(0).(entities.EvalResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entities.Logger, entities.MATLABSessionClient, evalmatlabcode.Args) error); ok {
		r1 = returnFunc(ctx, sessionLogger, client, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMATLABCodeEvaluator_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockMATLABCodeEvaluator_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionLogger entities.Logger
//   - client entities.MATLABSessionClient
//   - request evalmatlabcode.Args
func (_e *MockMATLABCodeEvaluator_Expecter) Execute(ctx interface{}, sessionLogger interface{}, client interface{}, request interface{}) *MockMATLABCodeEvaluator_Execute_Call {
	return &MockMATLABCodeEvaluator_Execute_Call{Call: _e.mock.On("Execute", ctx, sessionLogger, client, request)}
}

func (_c *MockMATLABCodeEvaluator_Execute_Call) Run(run func(ctx context.Context, sessionLogger entities.Logger, client entities.MATLABSessionClient, request evalmatlabcode.Args)) *MockMATLABCodeEvaluator_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 entities.Logger
		if args[1] != nil {
			arg1 = args[1].(entities.Logger)
		}
		var arg2 entities.MATLABSessionClient
		if args[2] != nil {
			arg2 = args[2].(entities.MATLABSessionClient)
		}
		var arg3 evalmatlabcode.Args
		if args[3] != nil {
			arg3 = args[3].(evalmatlabcode.Args)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMATLABCodeEvaluator_Execute_Call) Return(evalResponse entities.EvalResponse, err error) *MockMATLABCodeEvaluator_Execute_Call {
	_c.Call.Return(evalResponse, err)
	return _c
}

func (_c *MockMATLABCodeEvaluator_Execute_Call) RunAndReturn(run func(ctx context.Context, sessionLogger entities.Logger, client entities.MATLABSessionClient, request evalmatlabcode.Args) (entities.EvalResponse, error)) *MockMATLABCodeEvaluator_Execute_Call {
	_c.Call.Return(run)
	return _c
}
