// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-server/internal/usecases/matlabcommandqueue"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMonitoring creates a new instance of MockMonitoring. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMonitoring(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMonitoring {
	mock := &MockMonitoring{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMonitoring is an autogenerated mock type for the Monitoring type
type MockMonitoring struct {
	mock.Mock
}

type MockMonitoring_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMonitoring) EXPECT() *MockMonitoring_Expecter {
	return &MockMonitoring_Expecter{mock: &_m.Mock}
}

// Subscribe provides a mock function for the type MockMonitoring
func (_mock *MockMonitoring) Subscribe(onEvent func(matlabcommandqueue.MonitoringEvent), onError func(error)) (matlabcommandqueue.MonitoringSubscription, error) {
	ret := _mock.Called(onEvent, onError)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 matlabcommandqueue.MonitoringSubscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(func(matlabcommandqueue.MonitoringEvent), func(error)) (matlabcommandqueue.MonitoringSubscription, error)); ok {
		return returnFunc(onEvent, onError)
	}
	if returnFunc, ok := ret.Get(0).(func(func(matlabcommandqueue.MonitoringEvent), func(error)) matlabcommandqueue.MonitoringSubscription); ok {
		r0 = returnFunc(onEvent, onError)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(matlabcommandqueue.MonitoringSubscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(func(matlabcommandqueue.MonitoringEvent), func(error)) error); ok {
		r1 = returnFunc(onEvent, onError)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMonitoring_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockMonitoring_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - onEvent func(matlabcommandqueue.MonitoringEvent)
//   - onError func(error)
func (_e *MockMonitoring_Expecter) Subscribe(onEvent interface{}, onError interface{}) *MockMonitoring_Subscribe_Call {
	return &MockMonitoring_Subscribe_Call{Call: _e.mock.On("Subscribe", onEvent, onError)}
}

func (_c *MockMonitoring_Subscribe_Call) Run(run func(onEvent func(matlabcommandqueue.MonitoringEvent), onError func(error))) *MockMonitoring_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(matlabcommandqueue.MonitoringEvent)
		if args[0] != nil {
			arg0 = args[0].(func(matlabcommandqueue.MonitoringEvent))
		}
		var arg1 func(error)
		if args[1] != nil {
			arg1 = args[1].(func(error))
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMonitoring_Subscribe_Call) Return(monitoringSubscription matlabcommandqueue.MonitoringSubscription, err error) *MockMonitoring_Subscribe_Call {
	_c.Call.Return(monitoringSubscription, err)
	return _c
}

func (_c *MockMonitoring_Subscribe_Call) RunAndReturn(run func(onEvent func(matlabcommandqueue.MonitoringEvent), onError func(error)) (matlabcommandqueue.MonitoringSubscription, error)) *MockMonitoring_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}
