// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockMonitoringSubscription creates a new instance of MockMonitoringSubscription. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMonitoringSubscription(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMonitoringSubscription {
	mock := &MockMonitoringSubscription{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMonitoringSubscription is an autogenerated mock type for the MonitoringSubscription type
type MockMonitoringSubscription struct {
	mock.Mock
}

type MockMonitoringSubscription_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMonitoringSubscription) EXPECT() *MockMonitoringSubscription_Expecter {
	return &MockMonitoringSubscription_Expecter{mock: &_m.Mock}
}

// Unsubscribe provides a mock function for the type MockMonitoringSubscription
func (_mock *MockMonitoringSubscription) Unsubscribe() {
	_mock.Called()
	return
}

// MockMonitoringSubscription_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type MockMonitoringSubscription_Unsubscribe_Call struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
func (_e *MockMonitoringSubscription_Expecter) Unsubscribe() *MockMonitoringSubscription_Unsubscribe_Call {
	return &MockMonitoringSubscription_Unsubscribe_Call{Call: _e.mock.On("Unsubscribe")}
}

func (_c *MockMonitoringSubscription_Unsubscribe_Call) Run(run func()) *MockMonitoringSubscription_Unsubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMonitoringSubscription_Unsubscribe_Call) Return() *MockMonitoringSubscription_Unsubscribe_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMonitoringSubscription_Unsubscribe_Call) RunAndReturn(run func()) *MockMonitoringSubscription_Unsubscribe_Call {
	_c.Run(run)
	return _c
}
