classdef MCPBuildToolPluginServiceTest < matlab.mock.TestCase
    %MCPBuildToolPluginServiceTest Tests for MCP Build Tool plugin services.

    % Copyright 2026 The MathWorks, Inc.

    methods (Access = private)
        function [factory, behavior] = createFactoryMock(testCase, verbosity)
            import matlab.mock.actions.AssignOutputs

            [factory, behavior] = testCase.createMock( ...
                ?matlab.buildtool.internal.services.plugins.MCPBuildToolPluginFactory, ...
                Strict=true ...
            );
            when( ...
                behavior.createPlugins(verbosity), ...
                AssignOutputs(matlab.buildtool.plugins.BuildRunnerPlugin.empty(1, 0)) ...
            );
        end
    end

    methods (Test)
        function testServiceDiscoveryFindsMCPBuildToolPluginService(testCase)
            % Arrange
            serviceClass = ?matlab.buildtool.internal.services.plugins.BuildRunnerPluginService;
            namespace = meta.package.fromName( ...
                "matlab.buildtool.internal.services.plugins" ...
            );
            locator = matlab.automation.internal.services.ServiceLocator.forNamespace( ...
                namespace ...
            );

            % Act
            serviceClasses = locator.locate(serviceClass);
            targetServiceClasses = serviceClasses( ...
                ismember( ...
                    string({serviceClasses.Name}), ...
                    "matlab.buildtool.internal.services.plugins.MCPBuildToolPluginService" ...
                ) ...
            );
            services = matlab.automation.internal.services.ServiceFactory.create( ...
                targetServiceClasses ...
            );

            % Assert
            testCase.verifyNumElements(targetServiceClasses, 1);
            testCase.verifyInstanceOf( ...
                services, ...
                ?matlab.buildtool.internal.services.plugins.MCPBuildToolPluginService ...
            );
        end

        function testProvidePluginsUsesConciseVerbosityByDefault(testCase)
            % Arrange
            verbosity = matlab.automation.Verbosity.Concise;
            [factory, behavior] = testCase.createFactoryMock(verbosity);
            service = matlab.buildtool.internal.services.plugins.MCPBuildToolPluginService( ...
                Factory=factory ...
            );

            % Act
            plugins = service.providePlugins(struct());

            % Assert
            testCase.verifyEmpty(plugins);
            testCase.verifyCalled( ...
                behavior.createPlugins(verbosity) ...
            );
        end

        function testProvidePluginsUsesExplicitVerbosity(testCase)
            % Arrange
            verbosity = matlab.automation.Verbosity.Verbose;
            [factory, behavior] = testCase.createFactoryMock(verbosity);
            service = matlab.buildtool.internal.services.plugins.MCPBuildToolPluginService( ...
                Factory=factory ...
            );

            % Act
            plugins = service.providePlugins(struct(Verbosity=verbosity));

            % Assert
            testCase.verifyEmpty(plugins);
            testCase.verifyCalled( ...
                behavior.createPlugins(verbosity) ...
            );
        end

        function testDefaultFactoryCreatesProgressAndDiagnosticsPlugins(testCase)
            % Arrange
            factory = matlab.buildtool.internal.services.plugins.DefaultMCPBuildToolPluginFactory();

            % Act
            plugins = factory.createPlugins(matlab.automation.Verbosity.Concise);

            % Assert
            testCase.verifyNumElements(plugins, 2);
            testCase.verifyInstanceOf( ...
                plugins(1), ...
                ?matlab.buildtool.plugins.BuildRunProgressPlugin ...
            );
            testCase.verifyInstanceOf( ...
                plugins(2), ...
                ?matlab.buildtool.plugins.DiagnosticsOutputPlugin ...
            );
        end
    end
end
