// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/matlab/matlab-mcp-server/internal/usecases/runmatlabbuildfile"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProgressReporter creates a new instance of MockProgressReporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProgressReporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProgressReporter {
	mock := &MockProgressReporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProgressReporter is an autogenerated mock type for the ProgressReporter type
type MockProgressReporter struct {
	mock.Mock
}

type MockProgressReporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProgressReporter) EXPECT() *MockProgressReporter_Expecter {
	return &MockProgressReporter_Expecter{mock: &_m.Mock}
}

// ReportProgress provides a mock function for the type MockProgressReporter
func (_mock *MockProgressReporter) ReportProgress(ctx context.Context, update runmatlabbuildfile.BuildProgressUpdate) error {
	ret := _mock.Called(ctx, update)

	if len(ret) == 0 {
		panic("no return value specified for ReportProgress")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, runmatlabbuildfile.BuildProgressUpdate) error); ok {
		r0 = returnFunc(ctx, update)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProgressReporter_ReportProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportProgress'
type MockProgressReporter_ReportProgress_Call struct {
	*mock.Call
}

// ReportProgress is a helper method to define mock.On call
//   - ctx context.Context
//   - update runmatlabbuildfile.BuildProgressUpdate
func (_e *MockProgressReporter_Expecter) ReportProgress(ctx interface{}, update interface{}) *MockProgressReporter_ReportProgress_Call {
	return &MockProgressReporter_ReportProgress_Call{Call: _e.mock.On("ReportProgress", ctx, update)}
}

func (_c *MockProgressReporter_ReportProgress_Call) Run(run func(ctx context.Context, update runmatlabbuildfile.BuildProgressUpdate)) *MockProgressReporter_ReportProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 runmatlabbuildfile.BuildProgressUpdate
		if args[1] != nil {
			arg1 = args[1].(runmatlabbuildfile.BuildProgressUpdate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProgressReporter_ReportProgress_Call) Return(err error) *MockProgressReporter_ReportProgress_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProgressReporter_ReportProgress_Call) RunAndReturn(run func(ctx context.Context, update runmatlabbuildfile.BuildProgressUpdate) error) *MockProgressReporter_ReportProgress_Call {
	_c.Call.Return(run)
	return _c
}
