// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/matlab/matlab-mcp-server/internal/usecases/runmatlabbuildfile"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProgressUpdateSource creates a new instance of MockProgressUpdateSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProgressUpdateSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProgressUpdateSource {
	mock := &MockProgressUpdateSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProgressUpdateSource is an autogenerated mock type for the ProgressUpdateSource type
type MockProgressUpdateSource struct {
	mock.Mock
}

type MockProgressUpdateSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProgressUpdateSource) EXPECT() *MockProgressUpdateSource_Expecter {
	return &MockProgressUpdateSource_Expecter{mock: &_m.Mock}
}

// NextProgressUpdate provides a mock function for the type MockProgressUpdateSource
func (_mock *MockProgressUpdateSource) NextProgressUpdate(ctx context.Context) (runmatlabbuildfile.BuildProgressUpdate, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for NextProgressUpdate")
	}

	var r0 runmatlabbuildfile.BuildProgressUpdate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (runmatlabbuildfile.BuildProgressUpdate, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) runmatlabbuildfile.BuildProgressUpdate); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(runmatlabbuildfile.BuildProgressUpdate)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProgressUpdateSource_NextProgressUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextProgressUpdate'
type MockProgressUpdateSource_NextProgressUpdate_Call struct {
	*mock.Call
}

// NextProgressUpdate is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProgressUpdateSource_Expecter) NextProgressUpdate(ctx interface{}) *MockProgressUpdateSource_NextProgressUpdate_Call {
	return &MockProgressUpdateSource_NextProgressUpdate_Call{Call: _e.mock.On("NextProgressUpdate", ctx)}
}

func (_c *MockProgressUpdateSource_NextProgressUpdate_Call) Run(run func(ctx context.Context)) *MockProgressUpdateSource_NextProgressUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProgressUpdateSource_NextProgressUpdate_Call) Return(buildProgressUpdate runmatlabbuildfile.BuildProgressUpdate, err error) *MockProgressUpdateSource_NextProgressUpdate_Call {
	_c.Call.Return(buildProgressUpdate, err)
	return _c
}

func (_c *MockProgressUpdateSource_NextProgressUpdate_Call) RunAndReturn(run func(ctx context.Context) (runmatlabbuildfile.BuildProgressUpdate, error)) *MockProgressUpdateSource_NextProgressUpdate_Call {
	_c.Call.Return(run)
	return _c
}
