// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-server/internal/usecases/matlabcommandqueue"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUsecase creates a new instance of MockUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecase {
	mock := &MockUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsecase is an autogenerated mock type for the Usecase type
type MockUsecase struct {
	mock.Mock
}

type MockUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecase) EXPECT() *MockUsecase_Expecter {
	return &MockUsecase_Expecter{mock: &_m.Mock}
}

// Enqueue provides a mock function for the type MockUsecase
func (_mock *MockUsecase) Enqueue(code string, projectPath string) (matlabcommandqueue.EnqueueResult, error) {
	ret := _mock.Called(code, projectPath)

	if len(ret) == 0 {
		panic("no return value specified for Enqueue")
	}

	var r0 matlabcommandqueue.EnqueueResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (matlabcommandqueue.EnqueueResult, error)); ok {
		return returnFunc(code, projectPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) matlabcommandqueue.EnqueueResult); ok {
		r0 = returnFunc(code, projectPath)
	} else {
		r0 = ret.Get(0).(matlabcommandqueue.EnqueueResult)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(code, projectPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsecase_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type MockUsecase_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - code string
//   - projectPath string
func (_e *MockUsecase_Expecter) Enqueue(code interface{}, projectPath interface{}) *MockUsecase_Enqueue_Call {
	return &MockUsecase_Enqueue_Call{Call: _e.mock.On("Enqueue", code, projectPath)}
}

func (_c *MockUsecase_Enqueue_Call) Run(run func(code string, projectPath string)) *MockUsecase_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsecase_Enqueue_Call) Return(enqueueResult matlabcommandqueue.EnqueueResult, err error) *MockUsecase_Enqueue_Call {
	_c.Call.Return(enqueueResult, err)
	return _c
}

func (_c *MockUsecase_Enqueue_Call) RunAndReturn(run func(code string, projectPath string) (matlabcommandqueue.EnqueueResult, error)) *MockUsecase_Enqueue_Call {
	_c.Call.Return(run)
	return _c
}
