// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProgressNotificationSender creates a new instance of MockProgressNotificationSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProgressNotificationSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProgressNotificationSender {
	mock := &MockProgressNotificationSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProgressNotificationSender is an autogenerated mock type for the ProgressNotificationSender type
type MockProgressNotificationSender struct {
	mock.Mock
}

type MockProgressNotificationSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProgressNotificationSender) EXPECT() *MockProgressNotificationSender_Expecter {
	return &MockProgressNotificationSender_Expecter{mock: &_m.Mock}
}

// NotifyProgress provides a mock function for the type MockProgressNotificationSender
func (_mock *MockProgressNotificationSender) NotifyProgress(ctx context.Context, params *mcp.ProgressNotificationParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for NotifyProgress")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *mcp.ProgressNotificationParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProgressNotificationSender_NotifyProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyProgress'
type MockProgressNotificationSender_NotifyProgress_Call struct {
	*mock.Call
}

// NotifyProgress is a helper method to define mock.On call
//   - ctx context.Context
//   - params *mcp.ProgressNotificationParams
func (_e *MockProgressNotificationSender_Expecter) NotifyProgress(ctx interface{}, params interface{}) *MockProgressNotificationSender_NotifyProgress_Call {
	return &MockProgressNotificationSender_NotifyProgress_Call{Call: _e.mock.On("NotifyProgress", ctx, params)}
}

func (_c *MockProgressNotificationSender_NotifyProgress_Call) Run(run func(ctx context.Context, params *mcp.ProgressNotificationParams)) *MockProgressNotificationSender_NotifyProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *mcp.ProgressNotificationParams
		if args[1] != nil {
			arg1 = args[1].(*mcp.ProgressNotificationParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProgressNotificationSender_NotifyProgress_Call) Return(err error) *MockProgressNotificationSender_NotifyProgress_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProgressNotificationSender_NotifyProgress_Call) RunAndReturn(run func(ctx context.Context, params *mcp.ProgressNotificationParams) error) *MockProgressNotificationSender_NotifyProgress_Call {
	_c.Call.Return(run)
	return _c
}
