// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/matlab/matlab-mcp-server/internal/usecases/runmatlabbuildfile"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProgressMonitor creates a new instance of MockProgressMonitor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProgressMonitor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProgressMonitor {
	mock := &MockProgressMonitor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProgressMonitor is an autogenerated mock type for the ProgressMonitor type
type MockProgressMonitor struct {
	mock.Mock
}

type MockProgressMonitor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProgressMonitor) EXPECT() *MockProgressMonitor_Expecter {
	return &MockProgressMonitor_Expecter{mock: &_m.Mock}
}

// Monitor provides a mock function for the type MockProgressMonitor
func (_mock *MockProgressMonitor) Monitor(ctx context.Context, reporter runmatlabbuildfile.ProgressReporter) error {
	ret := _mock.Called(ctx, reporter)

	if len(ret) == 0 {
		panic("no return value specified for Monitor")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, runmatlabbuildfile.ProgressReporter) error); ok {
		r0 = returnFunc(ctx, reporter)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProgressMonitor_Monitor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Monitor'
type MockProgressMonitor_Monitor_Call struct {
	*mock.Call
}

// Monitor is a helper method to define mock.On call
//   - ctx context.Context
//   - reporter runmatlabbuildfile.ProgressReporter
func (_e *MockProgressMonitor_Expecter) Monitor(ctx interface{}, reporter interface{}) *MockProgressMonitor_Monitor_Call {
	return &MockProgressMonitor_Monitor_Call{Call: _e.mock.On("Monitor", ctx, reporter)}
}

func (_c *MockProgressMonitor_Monitor_Call) Run(run func(ctx context.Context, reporter runmatlabbuildfile.ProgressReporter)) *MockProgressMonitor_Monitor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 runmatlabbuildfile.ProgressReporter
		if args[1] != nil {
			arg1 = args[1].(runmatlabbuildfile.ProgressReporter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProgressMonitor_Monitor_Call) Return(err error) *MockProgressMonitor_Monitor_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProgressMonitor_Monitor_Call) RunAndReturn(run func(ctx context.Context, reporter runmatlabbuildfile.ProgressReporter) error) *MockProgressMonitor_Monitor_Call {
	_c.Call.Return(run)
	return _c
}
