classdef DefaultMCPBuildToolPluginFactory < ...
        matlab.buildtool.internal.services.plugins.MCPBuildToolPluginFactory
    %DefaultMCPBuildToolPluginFactory Create the standard MCP Build Tool plugins.

    % Copyright 2026 The MathWorks, Inc.

    methods
        function plugins = createPlugins(~, verbosity)
            progressStream = mcpserver.internal.streams.ToMCP();
            diagnosticsStream = mcpserver.internal.streams.ToMCP();

            plugins = [ ...
                matlab.buildtool.plugins.BuildRunProgressPlugin.withVerbosity( ...
                    verbosity, progressStream), ...
                matlab.buildtool.plugins.DiagnosticsOutputPlugin( ...
                    diagnosticsStream, ...
                    LoggingLevel=verbosity, ...
                    OutputDetail=verbosity) ...
            ];
        end
    end
end
