// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/matlab/matlab-mcp-server/internal/usecases/matlabcommandqueue"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUsecase creates a new instance of MockUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsecase {
	mock := &MockUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsecase is an autogenerated mock type for the Usecase type
type MockUsecase struct {
	mock.Mock
}

type MockUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsecase) EXPECT() *MockUsecase_Expecter {
	return &MockUsecase_Expecter{mock: &_m.Mock}
}

// Poll provides a mock function for the type MockUsecase
func (_mock *MockUsecase) Poll() []matlabcommandqueue.Command {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Poll")
	}

	var r0 []matlabcommandqueue.Command
	if returnFunc, ok := ret.Get(0).(func() []matlabcommandqueue.Command); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]matlabcommandqueue.Command)
		}
	}
	return r0
}

// MockUsecase_Poll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Poll'
type MockUsecase_Poll_Call struct {
	*mock.Call
}

// Poll is a helper method to define mock.On call
func (_e *MockUsecase_Expecter) Poll() *MockUsecase_Poll_Call {
	return &MockUsecase_Poll_Call{Call: _e.mock.On("Poll")}
}

func (_c *MockUsecase_Poll_Call) Run(run func()) *MockUsecase_Poll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUsecase_Poll_Call) Return(commands []matlabcommandqueue.Command) *MockUsecase_Poll_Call {
	_c.Call.Return(commands)
	return _c
}

func (_c *MockUsecase_Poll_Call) RunAndReturn(run func() []matlabcommandqueue.Command) *MockUsecase_Poll_Call {
	_c.Call.Return(run)
	return _c
}
